apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  ### 如果取消annotations注释此storageclass将作为默认storageclass自动创建pv
  #annotations:
  #  storageclass.kubernetes.io/is-default-class: "true"
provisioner: vickey-wu.com/nfs
parameters:
  archiveOnDelete: "false"
